### ISSUE TITLE
trouble to compil

### ISSUE THREAD

**Issue by HughhguH** [epsilonrt/ttsplay#1]
Hi,

ttsplay looks great but I can't compil.

On raspberry, I have installed the dependencies
When I compil I have got this error

Check the target platform, you can use BOARD to force the target...
sh: 1: hardware-cpu: not found
BOARD not defined, Build for linux standard system...
[CC]             ttsplay.c
[CC]             audio.c
[LINK]           ttsplay
/usr/bin/ld: cannot find -lsysio
collect2: error: ld returned 1 exit status
Makefile:465: recipe for target 'ttsplay' failed
make: *** [ttsplay] Error 1

Any idea what is wrong?

**Comment by epsilonrt** [comment]
Hi
the repository was created a bit too quickly, it is in draft version ... I removed the dependency with my sysio project, it should work with the last commit. I will pass the project under CMake as soon as I have some spare time. Thank you for telling me if it works for you?

**Comment by HughhguH** [comment]
Hi,

Ok it works now. By the way, by chance is there any way to change the voice to another one? (for instance male instance of female)

Thank you very much

**Comment by epsilonrt** [comment]
Yes, ttsplay uses svox pico lib (as in Android). You will find plenty of voice files on the internet (system path /usr /share/pico/lang, custom path ~/.lang). read the documentation on svox pico lib. good luck.
